name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: prisma
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Set up MySQL
        run: |
          mysql --host=127.0.0.1 --password=prisma --user=root --database=mysql --execute 'CREATE DATABASE IF NOT EXISTS prisma;'

      - name: Install dependencies and playwright binaries
        run: pnpm install && pnpm playwright install chromium

      - name: Setup environment variables
        run: |
          cp .env.example .env
          echo "NEXTAUTH_SECRET=supersecret" >> .env

      - name: Push schema to database
        run: pnpx prisma db push

      - name: Build application
        run: pnpm build

      - name: Run all tests
        run: pnpm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: |
          pnpm lint
          pnpm format:check
        env:
          SKIP_ENV_VALIDATION: true

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run typecheck
        run: pnpm ts:check
